name: ikinyarwanda
description: Kinyarwanda language stories and games.

publish_to: "none"

version: 2.0.2+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.2.0
  responsive_builder: ^0.4.3
  shared_preferences: ^2.0.18
  stacked: ^3.1.0+2
  tuple: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  # flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  # icons_launcher: ^2.1.0

# icons_launcher:
#   image_path: "assets/icons/iOS_icon.png"
#   platforms:
#     android:
#       enable: false
#     ios:
#       enable: true
#       remove_alpha_ios: true

# flutter_native_splash:
#   color: "#FFFFFF"
#   image_ios: "assets/icons/iOS_icon.png"
#   ios_content_mode: center
#   android: false
#   ios: true
#   web: false
#   android_12:
#     color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/imikino_json/ibisakuzo_1/
    - assets/imikino_json/ibisakuzo_2/
    - assets/imikino_json/ikeshamvugo/
    - assets/imikino_json/imiganimigufi/
    - assets/imikino_json/incamarenga/
    - assets/isomero_json/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
